### ISSUE TITLE
it crashed,the log is "java.lang.NullPointerException: source".InputStream stream = Scripto.class.getResourceAsStream("/scripto.js"); stream is null, where is the file "/scripto.js",T can't find it.

### ISSUE THREAD

**Issue by jiudishihuang** [ImangazalievM/Scripto#1]

**Comment by jiudishihuang** [comment]
InputStream stream = Scripto.class.getResourceAsStream("/scripto.js");
stream is null, where is the file "/scripto.js",T can't find it.

**Comment by ImangazalievM** [comment]
Thanks for a notice! Added missing files in [c0ccf05 ](https://github.com/ImangazalievM/Scripto/commit/c2b90a9143e1883a85fadde9deb6d6493d28eff4) commit. Please update your project
